### ISSUE TITLE
facing run time error 

### ISSUE THREAD

**Issue by mimansha11** [LennoxLondoW/Step-by-Step-Guide-Creating-a-Document-Chat-Application-with-Flask-React-ChatGPT-and-Llama-Index#1]
Hey Hiee , I need your Help  i am facing run time error , Please help me to fixed that please!
ERROR
Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at Message (http://localhost:3000/static/js/bundle.js:141:33)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:30251:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:34222:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:35525:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:20507:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:20551:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:20608:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:40506:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:39754:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:39677:9)

**Comment by LennoxLondoW** [comment]
Hello Mimansha,

Can you share your source code with me?

**Comment by mimansha11** [comment]
Thank You 
the issue resolved
